/**
 * API Route: /api/slides
 * 
 * Returns pre-serialized MDX slides from state.json
 * Converts widget-based slides to MDX if needed and serializes them server-side
 */

import { NextResponse } from 'next/server';
import * as fs from 'fs';
import * as path from 'path';
import { serialize } from 'next-mdx-remote/serialize';
import he from 'he';

// Look for state.json in these locations
const STATE_JSON_PATHS = [
  // Development: relative to workspace root
  path.join(process.cwd(), '../../../../output/golden_set_mdx/state.json'),
  path.join(process.cwd(), '../../../../output/golden_set_mdx_v13/state.json'),
  path.join(process.cwd(), '../../../../output/state.json'),
  // Absolute paths for Windows
  'C:/Users/yidansun/newProject/gggg/output/golden_set_mdx/state.json',
  'C:/Users/wangchao/repos/gggg/output/golden_set_mdx/state.json',
  'C:/Users/wangchao/repos/gggg/output/golden_set_mdx_v13/state.json',
  'C:/Users/wangchao/repos/gggg/output/state.json',
];

interface Slide {
  mdx?: string;
}

interface StateJson {
  slides?: Slide[];
  presentation?: {
    theme?: string;
    title?: string;
  };
  /** React theme name from CLI --mdx-theme */
  mdx_theme?: string;
}

/**
 * Fix MDX content to handle multi-line text inside JSX tags
 * MDX doesn't allow blank lines or markdown syntax inside JSX elements
 * This converts multi-line <Text> content to multiple <Text> elements
 */
function fixMdxContent(mdx: string): string {
  // Split multi-line <Text> content into separate <Text> elements
  // Match <Text>content with newlines</Text>
  let fixed = mdx;
  
  // Fix <Text> tags with multi-line content - split into separate Text elements
  fixed = fixed.replace(/<Text>([^]*?)<\/Text>/g, (match, content) => {
    // If content has blank lines, split into separate <Text> elements
    const trimmed = content.trim();
    if (trimmed.includes('\n\n')) {
      // Split by blank lines and create separate Text elements
      const parts = trimmed.split(/\n\n+/).filter((p: string) => p.trim());
      return parts.map((part: string) => {
        // Replace single newlines with spaces for clean text
        const cleanPart = part.trim().replace(/\n/g, ' ');
        return `<Text>${cleanPart}</Text>`;
      }).join('\n  ');
    }
    // Single newlines - just replace with space
    return `<Text>${trimmed.replace(/\n/g, ' ')}</Text>`;
  });
  
  return fixed;
}

/**
 * Decode HTML entities in MDX content.
 */
function decodeHtmlEntities(mdx: string): string {
  return he.decode(mdx);
}

export async function GET(request: Request) {
  try {
    // Get path parameter from query string
    const { searchParams } = new URL(request.url);
    const outputPath = searchParams.get('path') || 'golden_set_mdx';
    
    // Build paths to check based on the requested output directory
    const pathsToCheck = [
      // Relative paths
      path.join(process.cwd(), `../../../../output/${outputPath}/state.json`),
      // Absolute path
      `C:/Users/yidansun/newProject/gggg/output/${outputPath}/state.json`,
    ];
    
    // Find state.json
    let stateJson: StateJson | null = null;
    let foundPath = '';
    
    for (const statePath of pathsToCheck) {
      try {
        if (fs.existsSync(statePath)) {
          const content = fs.readFileSync(statePath, 'utf-8');
          stateJson = JSON.parse(content);
          foundPath = statePath;
          break;
        }
      } catch {
        continue;
      }
    }
    
    if (!stateJson) {
      return NextResponse.json(
        { error: 'state.json not found', searched: pathsToCheck, requestedPath: outputPath },
        { status: 404 }
      );
    }
    
    const slides = stateJson.slides || [];
    
    // Build individual slide MDX content and serialize each
    const serializedSlides = [];
    
    for (let i = 0; i < slides.length; i++) {
      const slide = slides[i];
      
      // Use MDX content directly from state.json (generated by LLM)
      const mdxContent = slide.mdx || '';
      
      if (!mdxContent) {
        console.warn(`Slide ${i + 1} has no mdx field - skipping`);
        serializedSlides.push({
          source: null,
          slideNumber: i + 1,
          mdx: '',
          error: 'No MDX content in slide. Regenerate with --project react-mdx',
        });
        continue;
      }
      
      // Fix multi-line text content that MDX doesn't support
      // and decode HTML entities (e.g., &amp; -> &)
      const fixedMdx = fixMdxContent(decodeHtmlEntities(mdxContent));
      
      // Serialize the MDX content server-side
      try {
        const serialized = await serialize(fixedMdx, {
          mdxOptions: {
            development: process.env.NODE_ENV === 'development',
          },
        });
        serializedSlides.push({
          source: serialized,
          slideNumber: i + 1,
          mdx: fixedMdx,
        });
      } catch (serializeErr) {
        console.error(`Failed to serialize slide ${i + 1}:`, serializeErr);
        // Return error for this slide but continue with others
        serializedSlides.push({
          source: null,
          slideNumber: i + 1,
          mdx: fixedMdx,
          error: serializeErr instanceof Error ? serializeErr.message : 'Serialization failed',
        });
      }
    }
    
    return NextResponse.json({
      slides: serializedSlides,
      slideCount: slides.length,
      source: foundPath,
      theme: stateJson.mdx_theme || stateJson.presentation?.theme || 'business',
    });
    
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
