"""Subagent abstraction matching Claude's runSubagent pattern.

In Claude's model:
1. The orchestrator (content-manager SKILL) decides which subagent to call
2. It generates a `runSubagent({description, prompt})` call with dynamic params
3. The subagent runs with the generated prompt

This module provides:
- Subagent class: Loads skill via parser and executes with handler
- run_subagent(): Function matching Claude's runSubagent API
"""
import json
import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, TYPE_CHECKING

from cliv2.core.skill_parser import parse_skill, build_subagent_prompt, ParsedSkill
from cliv2.core import verbose_logger

if TYPE_CHECKING:
    from cliv2.skills.base import SkillHandler, SkillContext

logger = logging.getLogger(__name__)


@dataclass
class SubagentCall:
    """Represents a subagent call as generated by the orchestrator."""
    description: str
    prompt: str
    skill_name: Optional[str] = None  # Extracted from prompt


@dataclass
class SubagentResult:
    """Result from a subagent execution."""
    success: bool
    output: Any
    skill_name: str
    error: Optional[str] = None
    raw_output: Optional[str] = None  # Raw LLM output before parsing


class Subagent:
    """A subagent that executes a skill with pre-loaded context.
    
    Uses skill_parser to:
    1. Parse SKILL.md into structured components
    2. Analyze input requirements (what context to pre-load)
    3. Build clean prompts with context injection
    4. Parse output based on expected format
    """
    
    # Map skill names to SKILL.md paths
    SKILL_PATHS = {
        "research-agent": "research/SKILL.md",
        "research": "research/SKILL.md",
        "theme-generator": "theme/SKILL.md",
        "theme": "theme/SKILL.md",
        "storyline-planner": "storyline/SKILL.md",
        "storyline": "storyline/SKILL.md",
        "ant-paged-layout": "ant-paged-layout/SKILL.md",
        "paged-layout-content": "paged-layout/SKILL.md",
        "layout": "ant-paged-layout/SKILL.md",
        "ant-slides-export": "ant-export/SKILL.md",
        "slides-export": "export/SKILL.md",
        "export": "ant-export/SKILL.md",
        "layout-validator": "validator/SKILL.md",
        "validator": "validator/SKILL.md",
    }
    
    # Which stages need user instruction passed
    STAGES_WITH_USER_INSTRUCTION = {"theme", "storyline"}
    
    # Cache for parsed skills (class-level, shared across instances)
    _skill_cache: dict[str, "ParsedSkill"] = {}
    
    def __init__(self, skill_name: str, llm: Any, skills_dir: Optional[Path] = None):
        """Initialize subagent with a skill.
        
        Args:
            skill_name: Name of the skill (e.g., "research-agent", "theme-generator")
            llm: LLM instance for completion
            skills_dir: Base directory for skills (default: .claude/skills/)
        """
        self.skill_name = skill_name
        self.llm = llm
        
        if skills_dir is None:
            self.skills_dir = Path(__file__).parent.parent.parent / ".claude" / "skills"
        else:
            self.skills_dir = skills_dir
        
        # Parse skill using cached parser
        self.parsed_skill = self._parse_skill()
    
    def _parse_skill(self) -> ParsedSkill:
        """Parse skill from SKILL.md file (with caching)."""
        skill_path = self.SKILL_PATHS.get(self.skill_name)
        if not skill_path:
            raise ValueError(f"Unknown skill: {self.skill_name}")
        
        full_path = self.skills_dir / skill_path
        cache_key = str(full_path)
        
        # Check cache first
        if cache_key in Subagent._skill_cache:
            return Subagent._skill_cache[cache_key]
        
        if not full_path.exists():
            raise FileNotFoundError(f"Skill file not found: {full_path}")
        
        # Parse and cache
        parsed = parse_skill(full_path)
        Subagent._skill_cache[cache_key] = parsed
        logger.debug(f"[{self.skill_name}] Cached parsed skill from {skill_path}")
        
        return parsed
    
    @property
    def input_spec(self):
        """Get input requirements for this skill."""
        return self.parsed_skill.input_spec
    
    @property
    def output_format(self) -> str:
        """Get expected output format for this skill."""
        return self.parsed_skill.output_spec.format
    
    async def run_with_handler(
        self,
        handler: "SkillHandler",
        context: "SkillContext",
        max_completion_tokens: Optional[int] = None,
        use_minimal_prompt: bool = False,
    ) -> SubagentResult:
        """Execute subagent using a SkillHandler for prompt building.
        
        This is the preferred method - uses handler for:
        1. build_prompt(): Skill-specific prompt with context
        2. SKILL.md instructions as system prompt (unless minimal mode)
        3. Parse output based on handler's output format
        
        Args:
            handler: Skill handler for prompt building
            context: Pre-loaded context from SkillContext
            max_completion_tokens: Optional token limit for output
            use_minimal_prompt: If True, skip SKILL.md and use minimal system prompt
            
        Returns:
            SubagentResult with parsed output
        """
        from cliv2.skills.base import SkillHandler, SkillContext
        
        # System prompt - either full SKILL.md or minimal
        if use_minimal_prompt:
            system_prompt = f"""You are a {self.skill_name} agent. Output JSON only, no explanations."""
        else:
            system_prompt = self.parsed_skill.instructions
        
        system_prompt += """

=== EXECUTION MODE ===
You are running in DIRECT OUTPUT mode.
- MCP tools are NOT available - context is pre-loaded below
- Return output DIRECTLY (no tool calls, no XML tags)
- Your output will be saved by the pipeline (you don't need to save)
"""
        
        # User prompt = handler builds skill-specific prompt
        user_prompt = handler.build_prompt(context)
        
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]
        
        # Log LLM input sizes at INFO level for performance debugging
        total_input_chars = len(system_prompt) + len(user_prompt)
        logger.info(f"[{self.skill_name}] LLM Input: system={len(system_prompt)}, user={len(user_prompt)}, total={total_input_chars} chars")
        logger.debug(f"[{self.skill_name}] LLM Input - User prompt:\n{user_prompt[:2000]}{'...(truncated)' if len(user_prompt) > 2000 else ''}")
        if max_completion_tokens:
            logger.info(f"[{self.skill_name}] Max completion tokens: {max_completion_tokens}")
        
        # Verbose logging (full, untruncated)
        verbose_logger.log_llm_call(
            skill_name=self.skill_name,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
        )
        
        try:
            # Build completion kwargs
            completion_kwargs = {"messages": messages}
            if max_completion_tokens:
                completion_kwargs["max_completion_tokens"] = max_completion_tokens
            
            import time
            start_time = time.time()
            response = self.llm.completion(**completion_kwargs)
            elapsed = time.time() - start_time
            
            content = response.choices[0].message.content if hasattr(response, 'choices') else str(response)
            content = content.strip()
            
            # Log token usage if available
            if hasattr(response, 'usage') and response.usage:
                usage = response.usage
                prompt_tokens = getattr(usage, 'prompt_tokens', 0)
                completion_tokens = getattr(usage, 'completion_tokens', 0)
                # Handle reasoning tokens - may be nested in completion_tokens_details
                reasoning_tokens = 0
                if hasattr(usage, 'completion_tokens_details') and usage.completion_tokens_details:
                    details = usage.completion_tokens_details
                    if hasattr(details, 'reasoning_tokens'):
                        reasoning_tokens = details.reasoning_tokens or 0
                logger.info(f"[{self.skill_name}] Tokens: prompt={prompt_tokens}, completion={completion_tokens}, reasoning={reasoning_tokens}")
            
            # Log LLM output at INFO level
            logger.info(f"[{self.skill_name}] LLM Output: {len(content)} chars in {elapsed:.1f}s")
            logger.debug(f"[{self.skill_name}] LLM Output:\n{content[:2000]}{'...(truncated)' if len(content) > 2000 else ''}")
            
            # Verbose logging (full, untruncated response)
            verbose_logger.log_streaming_complete(self.skill_name, content)
            
            # Parse output based on handler's output format
            parsed_output = self._parse_output(content, handler.output_spec.format)
            
            return SubagentResult(
                success=True,
                output=parsed_output,
                skill_name=self.skill_name,
                raw_output=content,  # Preserve raw LLM output
            )
            
        except Exception as e:
            logger.error(f"[{self.skill_name}] LLM call failed: {e}")
            return SubagentResult(
                success=False,
                output=None,
                skill_name=self.skill_name,
                error=str(e),
            )
    
    async def run_with_handler_streaming(
        self,
        handler: "SkillHandler",
        context: "SkillContext",
    ):
        """Execute subagent with streaming LLM response.
        
        Uses LiteLLM directly for streaming since OpenHands LLM doesn't support it.
        
        Args:
            handler: Skill handler for prompt building
            context: Pre-loaded context from SkillContext
            
        Yields:
            String chunks from LLM response
        """
        import litellm
        from cliv2.skills.base import SkillHandler, SkillContext
        
        # System prompt = SKILL.md instructions (excluding Workflow section)
        system_prompt = self.parsed_skill.instructions + """

=== EXECUTION MODE ===
You are running in DIRECT OUTPUT mode.
- MCP tools are NOT available - context is pre-loaded below
- Return output DIRECTLY (no tool calls, no XML tags)
- Your output will be saved by the pipeline (you don't need to save)
"""
        
        # User prompt = handler builds skill-specific prompt
        user_prompt = handler.build_prompt(context)
        
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]
        
        # Log LLM input
        logger.debug(f"[{self.skill_name}] LLM Input (streaming) - System prompt length: {len(system_prompt)} chars")
        logger.debug(f"[{self.skill_name}] LLM Input (streaming) - User prompt length: {len(user_prompt)} chars")
        logger.debug(f"[{self.skill_name}] LLM Input (streaming) - User prompt:\n{user_prompt[:2000]}{'...(truncated)' if len(user_prompt) > 2000 else ''}")
        
        # Verbose logging (full, untruncated)
        verbose_logger.log_llm_call(
            skill_name=self.skill_name,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            streaming=True,
        )
        
        # Collect full response for verbose logging
        full_response_chunks = []
        
        try:
            # Get LLM config for direct litellm call
            model = self.llm.config.model
            api_key = self.llm.config.api_key
            base_url = self.llm.config.base_url
            api_version = self.llm.config.api_version
            
            # Convert SecretStr to plain string if needed
            if hasattr(api_key, 'get_secret_value'):
                api_key = api_key.get_secret_value()
            
            # Use litellm async streaming directly
            response = await litellm.acompletion(
                model=model,
                messages=messages,
                api_key=api_key,
                base_url=base_url,
                api_version=api_version,
                stream=True,
            )
            
            async for chunk in response:
                if hasattr(chunk, 'choices') and chunk.choices:
                    delta = chunk.choices[0].delta
                    if hasattr(delta, 'content') and delta.content:
                        full_response_chunks.append(delta.content)
                        yield delta.content
            
            # Verbose logging of complete streaming response
            if full_response_chunks:
                verbose_logger.log_streaming_complete(self.skill_name, "".join(full_response_chunks))
                        
        except Exception as e:
            logger.error(f"[{self.skill_name}] LLM streaming call failed: {e}")
            raise
    
    async def run_with_context(
        self,
        project_dir: str,
        project_context: dict,
        user_instruction: str = "",
    ) -> SubagentResult:
        """Execute subagent with pre-loaded context (legacy method).
        
        Prefer run_with_handler() for new code.
        
        Args:
            project_dir: Project directory path
            project_context: Pre-loaded context from MCP reads
            user_instruction: Optional user instruction (for theme/storyline)
            
        Returns:
            SubagentResult with parsed output
        """
        # Determine if this stage needs user instruction
        include_instruction = self.skill_name in self.STAGES_WITH_USER_INSTRUCTION
        
        # Build prompts using skill parser
        system_prompt, user_prompt = build_subagent_prompt(
            skill=self.parsed_skill,
            project_dir=project_dir,
            project_context=project_context,
            user_instruction=user_instruction,
            include_instruction_in_prompt=include_instruction,
        )
        
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]
        
        # Log LLM input
        logger.debug(f"[{self.skill_name}] LLM Input - System prompt length: {len(system_prompt)} chars")
        logger.debug(f"[{self.skill_name}] LLM Input - User prompt length: {len(user_prompt)} chars")
        logger.debug(f"[{self.skill_name}] LLM Input - User prompt:\n{user_prompt[:2000]}{'...(truncated)' if len(user_prompt) > 2000 else ''}")
        
        try:
            response = self.llm.completion(messages=messages)
            content = response.choices[0].message.content if hasattr(response, 'choices') else str(response)
            content = content.strip()
            
            # Log LLM output
            logger.debug(f"[{self.skill_name}] LLM Output length: {len(content)} chars")
            logger.debug(f"[{self.skill_name}] LLM Output:\n{content[:2000]}{'...(truncated)' if len(content) > 2000 else ''}")
            
            # Parse output based on skill's output spec
            parsed_output = self._parse_output(content, self.output_format)
            
            return SubagentResult(
                success=True,
                output=parsed_output,
                skill_name=self.skill_name,
            )
            
        except Exception as e:
            logger.error(f"[{self.skill_name}] LLM call failed: {e}")
            return SubagentResult(
                success=False,
                output=None,
                skill_name=self.skill_name,
                error=str(e),
            )
    
    async def run(self, prompt: str, output_format: str = "text") -> SubagentResult:
        """Execute the subagent with raw prompt (legacy method).
        
        Prefer run_with_context() for new code.
        """
        # Use raw skill content + override for legacy calls
        system_prompt = self.parsed_skill.instructions + """

=== EXECUTION MODE ===
You are running in DIRECT OUTPUT mode.
- MCP tools are NOT available
- Return output DIRECTLY (no tool calls, no XML tags)
"""
        
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ]
        
        # Log LLM input
        logger.debug(f"[{self.skill_name}] LLM Input - System prompt length: {len(system_prompt)} chars")
        logger.debug(f"[{self.skill_name}] LLM Input - User prompt length: {len(prompt)} chars")
        logger.debug(f"[{self.skill_name}] LLM Input - User prompt:\n{prompt[:2000]}{'...(truncated)' if len(prompt) > 2000 else ''}")
        
        try:
            response = self.llm.completion(messages=messages)
            content = response.choices[0].message.content if hasattr(response, 'choices') else str(response)
            content = content.strip()
            
            # Log LLM output
            logger.debug(f"[{self.skill_name}] LLM Output length: {len(content)} chars")
            logger.debug(f"[{self.skill_name}] LLM Output:\n{content[:2000]}{'...(truncated)' if len(content) > 2000 else ''}")
            
            parsed_output = self._parse_output(content, output_format)
            
            return SubagentResult(
                success=True,
                output=parsed_output,
                skill_name=self.skill_name,
            )
            
        except Exception as e:
            logger.error(f"[{self.skill_name}] LLM call failed: {e}")
            return SubagentResult(
                success=False,
                output=None,
                skill_name=self.skill_name,
                error=str(e),
            )
    
    def _parse_output(self, content: str, output_format: str) -> Any:
        """Parse output based on expected format."""
        if output_format == "json":
            try:
                # Strip markdown code blocks if present
                if content.startswith("```"):
                    parts = content.split("```")
                    if len(parts) >= 2:
                        content = parts[1]
                        if content.startswith("json"):
                            content = content[4:]
                return json.loads(content.strip())
            except json.JSONDecodeError:
                return {"raw": content, "parse_error": True}
        
        elif output_format == "jsx":
            # Strip markdown code blocks if present
            if content.startswith("```"):
                parts = content.split("```")
                if len(parts) >= 2:
                    content = parts[1]
                    if content.startswith("jsx") or content.startswith("tsx"):
                        content = content[3:]
            return content.strip()
        
        elif output_format == "mdx":
            # MDX format: YAML frontmatter + content blocks
            # Strip markdown code blocks if present
            if content.startswith("```"):
                parts = content.split("```")
                if len(parts) >= 2:
                    content = parts[1]
                    # Remove language identifier
                    for lang in ["mdx", "markdown", "md", "yaml"]:
                        if content.startswith(lang):
                            content = content[len(lang):]
                            break
            return content.strip()
        
        else:  # text/markdown
            return content


def extract_skill_from_prompt(prompt: str) -> Optional[str]:
    """Extract skill name from a subagent prompt.
    
    The orchestrator generates prompts like:
    "Use the research-agent skill.\n\nProject directory: ..."
    
    Args:
        prompt: The subagent prompt
        
    Returns:
        Skill name if found, None otherwise
    """
    # Match patterns like "Use the X skill" or "Use X skill"
    patterns = [
        r"Use the (\S+) skill",
        r"Use (\S+) skill",
        r"skill[:\s]+(\S+)",
    ]
    
    for pattern in patterns:
        match = re.search(pattern, prompt, re.IGNORECASE)
        if match:
            return match.group(1).strip(".")
    
    return None


async def run_subagent(
    description: str,
    prompt: str,
    llm: Any,
    output_format: str = "text",
    skills_dir: Optional[Path] = None,
) -> SubagentResult:
    """Run a subagent - matches Claude's runSubagent API.
    
    This is the function that gets called when the orchestrator generates:
    ```
    runSubagent({
      description: "Research topics",
      prompt: "Use the research-agent skill.\n\nProject directory: ..."
    })
    ```
    
    Args:
        description: Short description of the task (for logging)
        prompt: Full prompt including skill name and parameters
        llm: LLM instance
        output_format: Expected output format
        skills_dir: Base directory for skills
        
    Returns:
        SubagentResult with execution result
    """
    # Extract skill name from prompt
    skill_name = extract_skill_from_prompt(prompt)
    if not skill_name:
        return SubagentResult(
            success=False,
            output=None,
            skill_name="unknown",
            error=f"Could not extract skill name from prompt: {prompt[:100]}...",
        )
    
    # Create and run subagent
    subagent = Subagent(skill_name, llm, skills_dir)
    return await subagent.run(prompt, output_format)


def parse_subagent_calls(orchestrator_output: str) -> list[SubagentCall]:
    """Parse subagent calls from orchestrator output.
    
    The orchestrator might output structured calls like:
    ```json
    {
      "subagent_calls": [
        {"description": "Research topics", "prompt": "Use the research-agent skill..."},
        {"description": "Generate theme", "prompt": "Use the theme-generator skill..."}
      ]
    }
    ```
    
    Args:
        orchestrator_output: Raw output from orchestrator LLM
        
    Returns:
        List of SubagentCall objects
    """
    calls = []
    
    try:
        # Try to parse as JSON
        if "```json" in orchestrator_output:
            json_match = re.search(r"```json\s*(.*?)\s*```", orchestrator_output, re.DOTALL)
            if json_match:
                orchestrator_output = json_match.group(1)
        
        data = json.loads(orchestrator_output)
        
        if "subagent_calls" in data:
            for call_data in data["subagent_calls"]:
                skill_name = extract_skill_from_prompt(call_data.get("prompt", ""))
                calls.append(SubagentCall(
                    description=call_data.get("description", ""),
                    prompt=call_data.get("prompt", ""),
                    skill_name=skill_name,
                ))
        
    except json.JSONDecodeError:
        # Not JSON, might be structured text
        pass
    
    return calls
