import React from 'react';

export interface InventComponentProps {
  name: string;
  [key: string]: any;
}

export const InventComponent: React.FC<InventComponentProps> = ({ name, ...props }) => {
  return (
    <div className="w-full p-4 border-2 border-dashed border-indigo-300 rounded-lg bg-indigo-50/50 flex flex-col items-center justify-center min-h-[200px] text-center">
      <div className="text-xl font-semibold text-indigo-800 mb-2">
        Generated Component: {name}
      </div>
      <div className="text-sm text-indigo-600 max-w-md">
        This component has been generated by the AI but needs to be built into the application to render fully.
      </div>
      <div className="mt-4 text-xs font-mono bg-white p-2 rounded border border-indigo-100 text-indigo-400 w-full overflow-hidden text-ellipsis whitespace-nowrap">
        {JSON.stringify(props)}
      </div>
    </div>
  );
};
